apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-v1
spec:
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      containers:
        - name: backend
          image: gcr.io/hightowerlabs/backend:v1
          imagePullPolicy: Always
          env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster
                  key: region
          args:
            - "-grpc=0.0.0.0:8080"
            - "-health=0.0.0.0:8008"
            - "-region=$(REGION)"
          ports:
            - name: grpc
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 20M
            requests:
              cpu: 100m
              memory: 10M
